package com.example.stepbystep.ui.saveroute

import android.content.Context
import android.util.Log
import androidx.lifecycle.*
import com.example.stepbystep.data.local.RouteRoomDatabase
import com.example.stepbystep.data.repository.RouteRepository
import com.example.stepbystep.domain.model.Route
import com.example.stepbystep.domain.model.Point
import com.google.android.gms.maps.model.LatLng
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.*

class SaveRouteViewModel(context: Context) : ViewModel() {
    
    private val repository: RouteRepository
    
    init {
        val database = RouteRoomDatabase.getInstance(context)
        repository = RouteRepository(database.routeDao())
    }

    // Route data to save
    private val _distance = MutableLiveData<Double>()
    val distance: LiveData<Double> = _distance

    private val _duration = MutableLiveData<Long>()
    val duration: LiveData<Long> = _duration

    private val _elevationGain = MutableLiveData<Double>()
    val elevationGain: LiveData<Double> = _elevationGain

    private val _elevation = MutableLiveData<Double>()
    val elevation: LiveData<Double> = _elevation

    private val _date = MutableLiveData<String>()
    val date: LiveData<String> = _date

    private val _imagePath = MutableLiveData<String?>()
    val imagePath: LiveData<String?> = _imagePath

    private val _altitudes = MutableLiveData<DoubleArray>()

    // Form fields
    val routeName = MutableLiveData<String>()
    val routeDescription = MutableLiveData<String>()
    
    // Route points for the map
    private val _routePoints = MutableLiveData<List<LatLng>>()
    val routePoints: LiveData<List<LatLng>> = _routePoints

    // Form validation
    val isFormValid = MediatorLiveData<Boolean>().apply {
        addSource(routeName) { validateForm() }
        addSource(routeDescription) { validateForm() }
    }

    // Set the route data from NewRouteActivity
    fun setRouteData(
        distance: Double,
        duration: Long,
        elevationGain: Double,
        elevation: Double,
        points: List<LatLng>,
        altitudes: DoubleArray? = null,
        isImported: Boolean = false  // Añadir parámetro para rutas importadas
    ) {
        _distance.value = distance
        _duration.value = duration
        _elevationGain.value = elevationGain
        _elevation.value = elevation
        _routePoints.value = points
        _altitudes.value = altitudes
        
        // Set current date as default
        val formatter = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        _date.value = formatter.format(Date())
        
        // Solo establecer un nombre predeterminado si no es una ruta importada
        // o si el nombre actual está vacío
        if (!isImported && (routeName.value.isNullOrEmpty())) {
            val timeFormatter = SimpleDateFormat("HH:mm", Locale.getDefault())
            routeName.value = "Ruta ${timeFormatter.format(Date())}"
        }
    }

    fun setImagePath(path: String?) {
        _imagePath.value = path
    }

    private fun validateForm() {
        val name = routeName.value
        val description = routeDescription.value
        isFormValid.value = !name.isNullOrBlank() && !description.isNullOrBlank()
    }

    fun saveRoute() {
        if (isFormValid.value != true) return
        
        val points = _routePoints.value ?: emptyList()
        val altitudes = _altitudes.value
        
        // Verificar el valor del path de la imagen antes de crear la ruta (nuevo código)
        Log.d("SaveRoute", "imagePath before creating Route: ${imagePath.value}")
        
        val routePoints = if (altitudes != null && altitudes.size == points.size) {
            // Use individual altitude for each point
            points.mapIndexed { index, latLng -> 
                Point(
                    latitude = latLng.latitude,
                    longitude = latLng.longitude,
                    altitude = altitudes[index],
                    timestamp = 0L
                )
            }
        } else {
            // Fallback in case altitude data is missing
            points.map { 
                Point(
                    latitude = it.latitude,
                    longitude = it.longitude,
                    altitude = _elevation.value ?: 0.0,
                    timestamp = 0L
                )
            }
        }
        
        val route = Route(
            id = 0, // Will be generated by Room
            name = routeName.value ?: "",
            description = routeDescription.value ?: "",
            date = date.value ?: "",
            distance = distance.value ?: 0.0,
            duration = duration.value ?: 0L,
            elevation = elevation.value ?: 0.0,
            elevationGain = elevationGain.value ?: 0.0,
            imagePath = imagePath.value,  // Asegurarnos de que esto no sea null
            points = routePoints
        )
        
        // Log para verificar que la ruta tiene el path de la imagen (nuevo código)
        Log.d("SaveRoute", "Route created with imagePath: ${route.imagePath}")
        
        viewModelScope.launch {
            repository.addRoute(route)
        }
    }
}